# -*- coding: utf-8 -*-
"""Assignment 1 week 3.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1abZvqXQHSzqQKde5zptNufm6VybHOuLb
"""

import pandas as pd

df = pd.read_csv("agriculture_yield_dataset.csv")

print("Rows and Columns:", df.shape)
print("\nColumn Names:")
print(df.columns)

print("\nFirst 10 Records:")
print(df.head(10))

print(df.dtypes)

print("\nMissing Values:")
print(df.isnull().sum())

stats = df.describe()
print(stats)

import matplotlib.pyplot as plt

cols = ['rainfall_mm','temperature_c',
        'fertilizer_kg','yield_ton_per_hectare']

for col in cols:
    plt.figure(figsize=(5,4))
    plt.hist(df[col], bins=20)
    plt.title(col)
    plt.show()

print(df['crop_type'].value_counts())

df['crop_type'].value_counts().plot(kind='bar')
plt.show()

print(df['soil_type'].value_counts())

df['soil_type'].value_counts().plot(kind='bar')
plt.show()

plt.hist(df['yield_ton_per_hectare'], bins=20)
plt.title("Yield Distribution")
plt.show()

plt.scatter(df['rainfall_mm'],
            df['yield_ton_per_hectare'])
plt.xlabel("Rainfall")
plt.ylabel("Yield")
plt.show()

plt.scatter(df['fertilizer_kg'],
            df['yield_ton_per_hectare'])
plt.xlabel("Fertilizer")
plt.ylabel("Yield")
plt.show()

import seaborn as sns

corr = df.corr(numeric_only=True)

print(corr)

sns.heatmap(corr,
            annot=True,
            cmap="coolwarm")
plt.show()

crop_avg = df.groupby('crop_type')[
'yield_ton_per_hectare'].mean()

soil_avg = df.groupby('soil_type')[
'yield_ton_per_hectare'].mean()

print(crop_avg)
print(soil_avg)

df_encoded = pd.get_dummies(
    df,
    columns=['crop_type','soil_type'],
    drop_first=True
)

print(df_encoded.head())

X = df_encoded.drop(
    'yield_ton_per_hectare',
    axis=1
)

y = df_encoded[
    'yield_ton_per_hectare'
]

print(X.head())
print(y.head())

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.20,
    random_state=42
)

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(X_train, y_train)

print("Intercept:")
print(model.intercept_)

print("\nCoefficients:")
for name, coef in zip(X.columns,
                      model.coef_):
    print(name, coef)